---
  title: "Determining Relationships Between Hospital Pricing and Various Considerations: Final Report"
  subtitle: "Data Science I: Foundations - Fall 2021 - Georgetown University"
  author: "Ryan Ripper"
  date: 12/17/2021 
  output: 
    html_document:
      css: style.css
---

#### __Word Count__: `r as.integer(sub("(\\d+).+$", "\\1", system(sprintf("wc -w %s", knitr::current_input()), intern = TRUE)))`

### *1. Introduction*

As of late, healthcare pricing has become a much-discussed topic as the Centers for Medicare and Medicaid Services (CMS) has introduced regulations mandating hospitals across the United States to publish corresponding procedural pricing. The publication of pricing for healthcare providers empowers the "shopper," the American citizen, to evaluate which hospital best fits their individual economic situation.^[Centers for Medicare & Medicaid Services. (2020, October 29). Press release CMS completes historic price transparency initiative. CMS. Retrieved November 1, 2021, from https://www.cms.gov/newsroom/press-releases/cms-completes-historic-price-transparency-initiative.] This wealth of data introduced to the general public can potentially give insight to pricing schedules, possibly accounting for a hospital's geographic and surrounding demographic considerations. In this project, we have attempted to build a machine learning model to predict healthcare pricing for a specific common procedure that has been desginated as "shoppable" by CMS. We will briefly discuss the background regarding hospital pricing with respect to the CMS mandates along with a discussion of the data collected and used to build our model. Ultimately, we will analyze the results of our model's predictive power and discuss further considerations with continuing further research regarding the topic.

### *2. Problem Statement and Background*

The American consumer has the expectation to determine which good best aligns with their socioeconomic situation and also which good they would ultimately prefer. These expectations have stirred the ever unchaging healthcare environment to evolve to meet today's standard. As the Centers for Medicare and Medicaid services has mandated for hospitals to publish their prices made readily accessible to patients, health systems have attempted to bridge the gap between healthcare costs and prices. 

### *3. Data*

### *4. Analysis*

### *5. Results*

### *6. Discussion*